# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
# Note: This operator does not define custom CRDs, it works with existing Kubernetes resources.
# If CRDs are added in the future, they will be generated in bases/ by 'make manifests'
resources: []

